#!/bin/bash
#t last
#str_op
#   rhost   (required)
#   port    (optional)
#end_op
#str_info
#   this is a script that just runnes nmap -sV with the given ip and port
#end_info
#
if [[ -z "$rhost" ]]; then
    echo "Please provide a target"
else
    if [[ -z "$port" ]]; then
        nmap -sV $rhost
    else
        nmap -sV $rhost -p $port
    fi
fi
